image:
  - Visual Studio 2019
configuration:
  - Release
before_build:
- cmd: >-
    git clone https://github.com/SFML/SFML.git

    cd SFML

    mkdir install

    mkdir build

    cd build

    cmake -G"Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install -DBUILD_SHARED_LIBS=FALSE -DSFML_USE_STATIC_STD_LIBS=TRUE ..

    cmake --build . --config Release --target install

    cd ../../

    dir

    mkdir SmallGameEngine

    mkdir build

    cd build

    cmake -G"Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../SmallGameEngine -DSMALLGAMEENGINE_STATIC_STD_LIBS=TRUE -DSFML_STATIC_LIBRARIES=TRUE -DSFML_DIR=C:/projects/smallgameengine/SFML/install/lib/cmake/SFML ..
build:
  project: build/INSTALL.vcxproj
  parallel: true
  verbosity: minimal
after_build:
- cmd: >-
    cd ../../

    7z a SmallGameEngine-Windows.zip C:/projects/smallgameengine/SmallGameEngine/ -r
artifacts:
- path: SmallGameEngine-Windows.zip
  name: SmallGameEngine-Windows
deploy:
  release: SmallGameEngine
  description: 'SmallGameEngine master branch release'
  provider: GitHub
  artifact: SmallGameEngine-windows.zip
  auth_token:
    secure: Pf37BCPu6ikFu98Rs0MDhDXzI995HHk0p0J5gPV8iy+3E20Vbdp1G6c9qVruQ0hn
  on:
    tags: true
