notifications:
  email: false
language:
- cpp
addons:
  apt:
    packages:
    - libgl1-mesa-dev
    - libopenal-dev
    - libjpeg-dev
    - libudev-dev
    - libxrandr-dev
    - libfreetype6-dev
    - libvorbis-dev
    - libflac-dev
  homebrew:
    packages:
     - cmake
    update: true
matrix:
  include:
  - name: "Ubuntu Bionic 18.04 GCC"
    os: linux
    dist: bionic
    compiler: gcc
  - name: "Ubuntu Bionic 18.04 Clang"
    os: linux
    dist: bionic
    compiler: clang
  - name: "macOS 10.14 GCC"
    os: osx
    osx_image: xcode11.3
    compiler: gcc
  - name: "macOS 10.14 Clang"
    os: osx
    osx_image: xcode11.3
    compiler: clang
  - name: "Windows GCC"
    os: windows
    compiler: gcc
install:
- git clone https://github.com/SFML/SFML.git
- cd SFML
- mkdir install
- mkdir build
- cd build
- cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_INSTALL_FRAMEWORK_PREFIX=../install -DSFML_BUILD_FRAMEWORKS=FALSE -DBUILD_SHARED_LIBS=TRUE ..
- cmake --build . --config Release --target install
- cd ../../
script:
- mkdir install/
- mkdir install/SmallGameEngine
- cmake -DCMAKE_INSTALL_PREFIX=./install/SmallGameEngine -DSFML_DIR=./SFML/install/lib/cmake/SFML .
- cmake --build . --config Release --target install
before_deploy:
  - zip SmallGameEngine-$TRAVIS_OS_NAME ./install/SmallGameEngine/ -r
  - ls # To check the zip file is created correctly
deploy:
  release: SmallGameEngine
  description: 'SmallGameEngine master branch release'
  skip_cleanup: true
  provider: releases
  api_key:
    secure: n5YYrvLk5Ft1l7lPmJtLHeS6CzP9Ug76cpuG57EzDFatUHa376mwi2US3eevImQ9I09KFtcFOFpqSphEvyvtIVhMsGkhm89kJn/inSmBOkmWWasN/m2chDTic0SnfoiwbYozIfqCJ5PIW+nRgwGY65np4GInnixcfaK5giaGBrI=
  file: SmallGameEngine-$TRAVIS_OS_NAME.zip
  on:
    tags: true
